name: Automatic tag

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.PAT }}
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
 
    # Create tag
    - name: Create tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: "0."      # gera a tag com o prefix "0."
        default_bump: false   # se nenhuma informação do tipo do commit for passado na mensagem de merge, não gera tag
